mysql:
    addr: 124.221.217.82:3306
    dbname: gvts
    password: abc123..
    username: root
other:
    redisuserprefix: 'user:'
    serverurl: 0.0.0.0:9001
redis:
    addr: 124.221.217.82:6379
token:
    refresh_secret: go-vue-ts-refresh-secret
    secret: go-vue-ts-secret
